services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - backend/.env
      - backend/mqtt_topics.env
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python main.py
    networks:
      - iot-net

networks:
  iot-net: