version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
      - mqtt_topics.env
    networks:
      - iot-net

networks:
  iot-net: